DangAnhPhu_61134177/BaiTap5_61134177/Models/EmpModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BaiTap5_61134177.Models
{
    public class EmpModel
    {
        public string EmpID { get; set; }
        public string Name { get; set; }
        public DateTime BirthOfDate { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Department { get; set; }
        public string Avatar { get; set; }
    }
}

DangAnhPhu_61134177/BaiTap5_61134177/Models/MailModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BaiTap5_61134177.Models
{
    public class MailModel
    {
        public string From { get; set; }
        public string Password { get; set; }
        public string To { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
    }
}

DangAnhPhu_61134177/BaiTap5_61134177/Controllers/AnhPhu_61134177Controller.cs
using BaiTap5_61134177.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaiTap5_61134177.Controllers
{
    public class AnhPhu_61134177Controller : Controller
    {
        // GET: AnhPhu_61134177
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Default()
        {
            return View();
        }

        public ActionResult SendMail()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SendMail(MailModel model)
        {
            System.Net.Mail.MailMessage mail = new System.Net.Mail.MailMessage();
            mail.From = new System.Net.Mail.MailAddress(model.From);
            mail.To.Add(model.To);
            mail.Subject = model.Subject;
            mail.Body = model.Body;
            mail.IsBodyHtml = true;
            System.Net.Mail.SmtpClient smtp = new System.Net.Mail.SmtpClient("smtp.gmail.com", 587);
            smtp.Credentials = new System.Net.NetworkCredential(model.From, model.Password);
            smtp.EnableSsl = true;
            smtp.Send(mail);
            return RedirectToAction("SendMail", "SendMail");
        }

        public ActionResult RegisterEmp()
        {
            return View();
        }

        public ActionResult Confirm(HttpPostedFileBase Avatar, EmpModel emp)
        {//Lấy thông tin từ input type=file có tên Avatar
            string postedFileName = System.IO.Path.GetFileName(Avatar.FileName);
            //Lưu hình đại diện về Server
            var path = Server.MapPath("/Images/" + postedFileName);
            Avatar.SaveAs(path);
            string fSave = Server.MapPath("/emp.txt");
            string[] emInfo = {
                emp.EmpID, emp.Name, emp.BirthOfDate.ToShortDateString(),
                emp.Email,emp.Password,emp.Department, postedFileName
            };
            //Lưu các thông ti vào tập tin emp.txt
            System.IO.File.WriteAllLines(fSave, emInfo);
            //Ghi nhận các thông tin đăng ký để hiện thị trên View Confirm
            ViewBag.EmpID = emInfo[0];
            ViewBag.Name = emInfo[1];
            ViewBag.BirthOfDate = emInfo[2].ToString();
            ViewBag.Email = emInfo[3];
            ViewBag.Password = emInfo[4];
            ViewBag.Department = emInfo[5];
            ViewBag.Avatar = "/Images/" + emInfo[6];
            return View();
        }

        public ActionResult ChangeBanner()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ChangeBanner(HttpPostedFileBase banner)
        {
            string postedFileName = System.IO.Path.GetFileName(banner.FileName);
            var path = Server.MapPath("/Images/" + postedFileName);
            banner.SaveAs(path);
            string fSave = Server.MapPath("/Banner.txt");
            System.IO.File.WriteAllText(fSave, postedFileName);
            return View();
        }
    }
}

DangAnhPhu_61134177/BaiTap5_61134177/Views/AnhPhu_61134177/ChangeBanner.cshtml
@{
    ViewBag.Title = "ChangeBanner";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm("ChangeBanner", "AnhPhu_61134177/ChangeBanner",
FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <p>
        <h3> <b>THAY ĐỔI BANNER</b></h3>
    </p>
    <hr />
    <p>
        Chọn ảnh làm banner: &nbsp;
        <input type="file" style="height:30px;" name="banner" accept="image/*" required /> <br>
        <input type="submit" style="height:30px; width:80px" value="Thay đổi" /><br>
    </p>
}

DangAnhPhu_61134177/BaiTap5_61134177/Views/AnhPhu_61134177/Confirm.cshtml
@{
    ViewBag.Title = "Confirm";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<h4>THÔNG TIN SINH VIÊN ĐÃ ĐĂNG KÍ</h4>
<table>
    <tr>
        <td>
            <table>
                <tr>
                    <td rowspan="6">
                        <a href="@Url.Action("Images/AnhPhu_61134177")">
                            <img src="@ViewBag.Avatar" width="100" height="100" />
                        </a>
                    </td>
                    <td>Mã nhân viên:</td>
                    <td>@ViewBag.EmpId</td>
                </tr>
                <tr>
                    <td>Họ và tên:</td>
                    <td>@ViewBag.Name</td>
                </tr>
                <tr>
                    <td>Ngày sinh:</td>
                    <td>@ViewBag.BirthOfDate</td>
                </tr>
                <tr>
                    <td>Email:</td>
                    <td>@ViewBag.Email</td>
                </tr>
                <tr>
                    <td>Mật khẩu :</td>
                    <td>@ViewBag.Password</td>
                </tr>
                <tr>
                    <td>Phòng ban:</td>
                    <td>@ViewBag.Department</td>
                </tr>
                <tr>
                    <td></td>
                    <td><a href="@Url.Action("RegisterEmp","AnhPhu_61134177")">Quay lại</a></td>
                </tr>
            </table>
        </td>
    </tr>
</table>

DangAnhPhu_61134177/BaiTap5_61134177/Views/AnhPhu_61134177/Default.cshtml
@{
    ViewBag.Title = "Default";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>DANH SÁCH CÁC BÀI TẬP</h2>

<ol>
    <li>
        Tạo một trang web thực hiện chức năng đăng ký thông tin nhân viên gồm các thông tin: Mã số nhân viên, họ tên, ngày sinh, email, mật khẩu,
        đơn vị và ảnh đại diện <br />
        Khi người dùng nhấn nút đăng ký, ứng dụng cho phép lưu thông tin nhân viên vừa nhập vào file text và lưu ở server (lưu cả hình về server)
        , ứng dụng cho phép mở thông tin cá nhân vừa đăng ký hiển thị lại client web.
    </li>
    <li>
        Tạo 1 trang web cho phép đăng nhập vào email.
    </li>
    <li>
        Tạo chức năng cho phép người dùng chọn 1 ảnh bất kỳ để thay đổi banner giao diện.
    </li>
</ol>

DangAnhPhu_61134177/BaiTap5_61134177/Views/AnhPhu_61134177/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="text-transform:uppercase; font-weight:bold">Nội Dung Thay Đổi</h2>

DangAnhPhu_61134177/BaiTap5_61134177/Views/AnhPhu_61134177/RegisterEmp.cshtml
@{
    ViewBag.Title = "RegisterEmp";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h4>THÔNG TIN THÀNH VIÊN ĐĂNG KÍ</h4>
<form name="f1" action="/AnhPhu_61134177/Confirm" method="post" enctype="multipart/form-data">
    <table>
        <tr>
            <td>Mã số nhân viên</td>
            <td><input type="text" name="EmpId" size="35" /></td>
        </tr>
        <tr>
            <td>Họ tên</td>
            <td><input type="text" name="Name" size="35" /></td>
        </tr>
        <tr>
            <td>Ngày sinh</td>
            <td><input type="date" name="BirthOfDate" size="35" /> </td>
        </tr>
        <tr>
            <td>Email</td>
            <td><input type="text" name="Email" size="35" /></td>
        </tr>
        <tr>
            <td> Mật khẩu</td>
            <td><input type="password" name="Password" size="35" /></td>
        </tr>
        <tr>
            <td>Đơn vị</td>
            <td><input type="text" name="Department" size="35" /></td>
        </tr>
        <tr>
            <td>Ảnh đại diện</td>
            <td><input type="file" name="Avatar" size="35" /></td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" name="Đăng kí" value="Đăng kí" />
            </td>
        </tr>
    </table>
</form>

DangAnhPhu_61134177/BaiTap5_61134177/Views/AnhPhu_61134177/SendMail.cshtml
@{
    ViewBag.Title = "SendMail";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<style>
    .wrapper textarea {
        width: 100%;
        resize: none;
        height: 59px;
        outline: none;
        padding: 15px;
        font-size: 16px;
        margin-top: 10px;
        border-radius: 5px;
        max-height: 330px;
        caret-color: #4671EA;
        border: 1px solid #bfbfbf;
    }

    textarea::placeholder {
        color: #b3b3b3;
    }

    textarea:is(:focus, :valid) {
        padding: 14px;
        border: 2px solid #4671EA;
    }

    textarea::-webkit-scrollbar {
        width: 0px;
    }
</style>

@Styles.Render("~/Content/css")
<h3 style="margin-top: -30px">CHỨC NĂNG GỬI EMAIL</h3>
<div class="container">
    <form action="/AnhPhu_61134177/SendMail" method="post">
        <div class="row" style="margin:10px">
            <div class="col-lg-2">
                Gửi từ email:
            </div>
            <div>
                <input type="email" name="From" />
            </div>
        </div>
        <div class="row" style="margin:10px">
            <div class="col-lg-2">
                Mật khẩu:
            </div>
            <div>
                <input type="text" name="Password" />
            </div>
        </div>
        <div class="row" style="margin:10px">
            <div class="col-lg-2">
                Gửi đến email:
            </div>
            <div>
                <input type="email" name="To" />
            </div>
        </div>
        <div class="row" style="margin:10px">
            <div class="col-lg-2">
                Tiêu đề:
            </div>
            <div>
                <input type="text" name="Subject" />
            </div>
        </div>
        <div class="row" style="margin:10px">
            <div class="col-lg-2">
                Nội dung:
            </div>
            <div class="wrapper">
                <textarea spellcheck="false" placeholder="Nhập nội dung tại đây" required></textarea>
            </div>
        </div>
        <div class="row" style="margin:10px">
            <input type="submit" value="Gửi email" class="col-lg-offset-2" />
        </div>
    </form>
</div>

<!--tự động resize Textarea-->
<script>
    const textarea = document.querySelector("textarea");
    textarea.addEventListener("keyup", e => {
        textarea.style.height = "63px";
        let scHeight = e.target.scrollHeight;
        textarea.style.height = `${scHeight}px`;
    });
</script>

DangAnhPhu_61134177/BaiTap5_61134177/Views/Shared/_LayoutAdmin.cshtml
@{
    var path = Server.MapPath("/Banner.txt");
    var fileImage = System.IO.File.ReadAllText(path);
    ViewBag.image = "/Images/" + fileImage;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/styleAdmin.css" rel="stylesheet" />
</head>
<body style="margin-top:0px;">
    <div id="banner"><img src=@ViewBag.image /></div>
    <div id="menu">
        <div>
            @Html.ActionLink("TRANG CHỦ", "Default", "/AnhPhu_61134177/Default", htmlAttributes: new
           { @class = "a" }) &nbsp;|&nbsp;
            @Html.ActionLink("ĐĂNG KÝ", "RegisterEmp", "AnhPhu_61134177/RegisterEmp",
           new { @class = "a" })&nbsp;|&nbsp;
            @Html.ActionLink("GỬI EMAIL", "SendMail", "/AnhPhu_61134177/SendMail", new
           { @class = "a" }) &nbsp;|&nbsp;
            @Html.ActionLink("THAY ĐỔI BANNER", "ChangeBanner",
           "AnhPhu_61134177/ChangeBanner", new { @class = "a" })
            <hr style="margin-top:0px;" />
        </div>
    </div>
    <div id="content">
        @RenderBody()
    </div>
    <div id="footer">
    </div>
</body>
</html>