DangAnhPhu_61134177/BaiTap2_61134177/Models/SinhVien.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BaiTap2_61134177.Models
{
    public class SinhVien
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Marks { get; set; }
    }
}

DangAnhPhu_61134177/BaiTap2_61134177/Controllers/SinhVien_61134177Controller.cs
using BaiTap2_61134177.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaiTap2_61134177.Controllers
{
    public class SinhVien_61134177Controller : Controller
    {
        // GET: SinhVien_61134177
        public ActionResult UseRequestIndex()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UseRequest()
        {
            string Id = Request["Id"];
            string Name = Request["Name"];
            double Marks = Convert.ToDouble(Request["Marks"]);
            ViewBag.Id = Id;
            ViewBag.Name = Name;
            ViewBag.Marks = Marks;
            return View(ViewBag);
        }

        //sử dụng Action
        public ActionResult UseActionIndex()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UseAction(string Id, string Name, string Marks)
        {
            ViewBag.Id = Id;
            ViewBag.Names = Name;
            ViewBag.Marks = Marks;

            return View(ViewBag);
        }

        //sử dụng FormCollection
        public ActionResult UseFormCollectionIndex()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UseFormCollection(FormCollection form)
        {
            ViewBag.Id = form["Id"];
            ViewBag.Name = form["Name"];
            ViewBag.Marks = form["Marks"];

            return View(ViewBag);
        }

        //sử dụng model
        public ActionResult UseModelIndex()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UseModel(SinhVien sv)
        {
            ViewBag.Id = sv.Id;
            ViewBag.Name = sv.Name;
            ViewBag.Marks = sv.Marks;

            return View(ViewBag);
        }
    }
}

DangAnhPhu_61134177/BaiTap2_61134177/Views/SinhVien_61134177/UseAction.cshtml
@{
    ViewBag.Title = "UseAction";
    Layout = null;
}

<h4>THÔNG TIN SINH VIÊN ĐÃ ĐĂNG KÍ</h4>
<table>
    <tr>
        <td>Mã sinh viên:  @ViewBag.Id</td>
    </tr>
    <tr>
        <td>Họ và tên:  @ViewBag.Name</td>
    </tr>
    <tr>
        <td>
            Điểm:  @ViewBag.Marks
        </td>
        <td>
            <a href="@Url.Action("UseActionIndex","SinhVien_61134177")">Quay lại</a>
        </td>
    </tr>
</table>

DangAnhPhu_61134177/BaiTap2_61134177/Views/SinhVien_61134177/UseActionIndex.cshtml
@{
    ViewBag.Title = "UseActionIndex";
    Layout = null;
}

<h4>THÔNG TIN SINH VIÊN</h4>
<form name="f1" action="/SinhVien_61134177/UseAction" method="post">
    <table>
        <tr>
            <td>
                Mã sinh viên:
            </td>
            <td>
                <input type="text" name="Id" />
            </td>
        </tr>
        <tr>
            <td>
                Họ và tên:
            </td>
            <td>
                <input type="text" name="Name" />
            </td>
        </tr>
        <tr>
            <td>
                Điểm:
            </td>
            <td>
                <input type="text" name="Marks" />
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" name="Đăng kí" value="Đăng kí" />
            </td>
        </tr>
    </table>
</form>

DangAnhPhu_61134177/BaiTap2_61134177/Views/SinhVien_61134177/UseFormCollection.cshtml
@{
    ViewBag.Title = "UseFormCollection";
    Layout = null;
}

<h4>THÔNG TIN SINH VIÊN ĐÃ ĐĂNG KÍ</h4>
<table>
    <tr>
        <td>Mã sinh viên:  @ViewBag.Id</td>
    </tr>
    <tr>
        <td>Họ và tên:  @ViewBag.Name</td>
    </tr>
    <tr>
        <td>
            Điểm:  @ViewBag.Marks
        </td>
        <td>
            <a href="@Url.Action("UseFormCollectionIndex","SinhVien_61134177")">Quay lại</a>
        </td>
    </tr>
</table>

DangAnhPhu_61134177/BaiTap2_61134177/Views/SinhVien_61134177/UseFormCollectionIndex.cshtml
@{
    ViewBag.Title = "UseFormCollectionIndex";
    Layout = null;
}

<h4>THÔNG TIN SINH VIÊN</h4>
<form name="f1" action="/SinhVien_61134177/UseFormCollection" method="post">

    <div>
        <table>
            <tr>
                <td>
                    Mã sinh viên:
                </td>
                <td>
                    <input type="text" name="Id" />
                </td>
            </tr>
            <tr>
                <td>
                    Họ và tên:
                </td>
                <td>
                    <input type="text" name="Name" />
                </td>
            </tr>
            <tr>
                <td>
                    Điểm:
                </td>
                <td>
                    <input type="text" name="Marks" />
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <input type="submit" name="Đăng kí" value="Đăng kí" />
                </td>
            </tr>
        </table>
    </div>
</form>

DangAnhPhu_61134177/BaiTap2_61134177/Views/SinhVien_61134177/UseModel.cshtml
@{
    ViewBag.Title = "UseModel";
    Layout = null;
}

<h4>THÔNG TIN SINH VIÊN ĐÃ ĐĂNG KÍ</h4>
<table>
    <tr>
        <td>Mã sinh viên:  @ViewBag.Id</td>
    </tr>
    <tr>
        <td>Họ và tên:  @ViewBag.Name</td>
    </tr>
    <tr>
        <td>
            Điểm:  @ViewBag.Marks
        </td>
        <td>
            <a href="@Url.Action("UseModelIndex","SinhVien_61134177")">Quay lại</a>
        </td>
    </tr>
</table>

DangAnhPhu_61134177/BaiTap2_61134177/Views/SinhVien_61134177/UseModelIndex.cshtml
@model BaiTap2_61134177.Models.SinhVien

@{
    ViewBag.Title = "UseModelIndex";
    Layout = null;
}

<h4>THÔNG TIN SINH VIÊN</h4>
<form name="f1" action="/SinhVien_61134177/UseModel" method="post">

    <div>
        <table>
            <tr>
                <td>
                    Mã sinh viên:
                </td>
                <td>
                    @Html.EditorFor(model => model.Id)
                </td>
            </tr>
            <tr>
                <td>
                    Họ và tên:
                </td>
                <td>
                    @Html.EditorFor(model => model.Name)
                </td>
            </tr>
            <tr>
                <td>
                    Điểm:
                </td>
                <td>
                    @Html.EditorFor(model => model.Marks)
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <input type="submit" name="Đăng kí" value="Đăng kí" />
                </td>
            </tr>
        </table>
    </div>
</form>

DangAnhPhu_61134177/BaiTap2_61134177/Views/SinhVien_61134177/UseRequest.cshtml
@{
    ViewBag.Title = "UseRequest";
    Layout = null;
}

<h4>THÔNG TIN SINH VIÊN ĐÃ ĐĂNG KÍ</h4>
<table>
    <tr>
        <td>Mã sinh viên:  @ViewBag.Id</td>
    </tr>
    <tr>
        <td>Họ và tên:  @ViewBag.Name</td>
    </tr>
    <tr>
        <td>
            Điểm:  @ViewBag.Marks
        </td>
        <td>
            <a href="@Url.Action("UseRequestIndex","SinhVien_61134177")">Quay lại</a>
        </td>
    </tr>
</table>

DangAnhPhu_61134177/BaiTap2_61134177/Views/SinhVien_61134177/UseRequestIndex.cshtml
@{
    ViewBag.Title = "UseRequestIndex";
    Layout = null;
}

<h4>THÔNG TIN SINH VIÊN</h4>
<form name="f1" action="/SinhVien_61134177/UseRequest" method="post">

    <div>
        <table>
            <tr>
                <td>
                    Mã sinh viên:
                </td>
                <td>
                    <input type="text" name="Id" />
                </td>
            </tr>
            <tr>
                <td>
                    Họ và tên:
                </td>
                <td>
                    <input type="text" name="Name" />
                </td>
            </tr>
            <tr>
                <td>
                    Điểm:
                </td>
                <td>
                    <input type="text" name="Marks" />
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <input type="submit" name="Đăng kí" value="Đăng kí" />
                </td>
            </tr>
        </table>
    </div>
</form>