DangAnhPhu_61134177/BaiTap3_61134177/Models/EmpModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BaiTap3_61134177.Models
{
    public class EmpModel
    {
        public string EmpID { get; set; }
        public string Name { get; set; }
        public DateTime BirthOfDate { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Department { get; set; }
        public string Avatar { get; set; }
    }
}

DangAnhPhu_61134177/BaiTap3_61134177/Controllers/NhanVien_61134177Controller.cs
using BaiTap3_61134177.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaiTap3_61134177.Controllers
{
    public class NhanVien_61134177Controller : Controller
    {
        // GET: NhanVien_61134177
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase Avatar, EmpModel emp)
        {
            //Lấy thông tin từ input type = file có tên Avatar
            string postedFileName = System.IO.Path.GetFileName(Avatar.FileName);
            //Lưu hình đại diện về Server
            var path = Server.MapPath("/images/" + postedFileName);
            Avatar.SaveAs(path);
            string fSave = Server.MapPath("/emp.txt");
            string[] emInfo = {
                emp.EmpID,
                emp.Name,
                emp.BirthOfDate.ToShortDateString(),
                emp.Email,emp.Password,
                emp.Department,
                postedFileName
            };
            //Lưu các thông tin vào tập tin emp.txt
            System.IO.File.WriteAllLines(fSave, emInfo);
            //Ghi nhận các thông tin đăng ký để hiện thị trên View Confirm
            ViewBag.EmpID = emInfo[0];
            ViewBag.Name = emInfo[1];
            ViewBag.BirthOfDate = emInfo[2].ToString();
            ViewBag.Email = emInfo[3];
            ViewBag.Password = emInfo[4];
            ViewBag.Department = emInfo[5];
            ViewBag.Avatar = "/images/" + emInfo[6];
            return View("Confirm");
        }

        public ActionResult Confirm(EmpModel emp)
        {
            return View();
        }
    }
}

DangAnhPhu_61134177/BaiTap3_61134177/Views/NhanVien_61134177/Confirm.cshtml
@{
    ViewBag.Title = "Confirm";
    Layout = null;
}
<h4>THÔNG TIN SINH VIÊN ĐÃ ĐĂNG KÍ</h4>
<table>
    <tr>
        <td>
            <table>

                <tr>
                    <td rowspan="6">
                        <a href="@Url.Action("images/NhanVien_61134177")">
                            <img src="@ViewBag.Avatar" width="100" height="100" />
                        </a>
                    </td>
                    <td>Mã nhân viên:</td>
                    <td>@ViewBag.EmpId</td>
                </tr>
                <tr>
                    <td>Họ và tên:</td>
                    <td>@ViewBag.Name</td>
                </tr>
                <tr>
                    <td>Ngày sinh:</td>
                    <td>@ViewBag.BirthOfDate</td>
                </tr>
                <tr>
                    <td>Email:</td>
                    <td>@ViewBag.Email</td>
                </tr>
                <tr>
                    <td>Mật khẩu :</td>
                    <td>@ViewBag.Password</td>
                </tr>
                <tr>
                    <td>Phòng ban:</td>
                    <td>@ViewBag.Department</td>
                </tr>
                <tr>
                    <td></td>
                    <td><a href="@Url.Action("Index","NhanVien_61134177")">Quay lại</a></td>
                </tr>
            </table>
        </td>
    </tr>
</table>

DangAnhPhu_61134177/BaiTap3_61134177/Views/NhanVien_61134177/Index.cshtml
@model BaiTap3_61134177.Models.EmpModel

@{
    ViewBag.Title = "Index";
    Layout = null;
}

<meta name="viewport" content="width=device-width" />
<title>Index</title>

<h4>THÔNG TIN THÀNH VIÊN ĐĂNG KÍ</h4>
@{Html.BeginForm("Index", "NhanVien_61134177", FormMethod.Post, new { enctype = "multipart/form-data" });}
<form name="f1" action="/NhanVien_61134177/Confirm" method="post" enctype="multipart/form-data">
    <table>
        <tr>
            <td>Mã số nhân viên</td>
            <td><input type="text" name="EmpId" size="35" /></td>
        </tr>
        <tr>
            <td>Họ tên</td>
            <td><input type="text" name="Name" size="35" /></td>
        </tr>
        <tr>
            <td>Ngày sinh</td>
            <td><input type="date" name="BirthOfDate" size="35" /> </td>
        </tr>
        <tr>
            <td>Email</td>
            <td><input type="text" name="Email" size="35" /></td>
        </tr>
        <tr>
            <td> Mật khẩu</td>
            <td><input type="password" name="Password" size="35" /></td>
        </tr>
        <tr>
            <td>Đơn vị</td>
            <td><input type="text" name="Department" size="35" /></td>
        </tr>
        <tr>
            <td>Ảnh đại diện</td>
            <td><input type="file" name="Avatar" size="35" /></td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" name="Đăng kí" value="Đăng kí" />
            </td>
        </tr>
    </table>
</form>

DangAnhPhu_61134177/BaiTap3_61134177/Views/NhanVien_61134177/TrangChu.cshtml
@{
    ViewBag.Title = "TrangChu";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="text-transform:uppercase; font-weight:bold">nội dung thay đổi</h2>